openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is the API documentation for my application
tags:
  - name: Contacts
    description: Operations related to contacts
  - name: Auth
    description: Authentication and password reset operations
servers:
  - url: http://127.0.0.1:3000
  - url: https://nodejs-hw-mongodb-by38.onrender.com
security:
  - bearerAuth: []
paths:
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: '../swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{contactId}/delete.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /auth/register:
    $ref: '../swagger/paths/auth/register.yaml'
  /auth/login:
    $ref: '../swagger/paths/auth/login.yaml'
  /auth/refresh:
    $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/logout:
    $ref: '../swagger/paths/auth/logout.yaml'
  /auth/send-reset-email:
    $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    $ref: '../swagger/paths/auth/reset-pwd.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
