openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is the API documentation for my application
tags:
  - name: contacts
    description: Operations related to contacts
  - name: auth
    description: Authentication and password reset operations
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-by38.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: './paths/contacts/{contactId}/get.yaml'
    patch:
      $ref: './paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: './paths/contacts/{contactId}/delete.yaml'
  /contacts:
    get:
      $ref: './paths/contacts/get.yaml'
    post:
      $ref: './paths/contacts/post.yaml'
  /auth/register:
    $ref: './paths/auth/register/post.yaml'
  /auth/login:
    $ref: './paths/auth/login/post.yaml'
  /auth/refresh:
    $ref: './paths/auth/refresh/post.yaml'
  /auth/logout:
    $ref: './paths/auth/logout/post.yaml'
  /auth/send-reset-email:
    $ref: './paths/auth/send-reset-email/post.yaml'
  /auth/reset-pwd:
    $ref: './paths/auth/reset-pwd/post.yaml'
components:
  schemas:
    $ref: './components/schemas.yaml'
  responses:
    $ref: './components/responses.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
